version: "3.3"
services:
  spark-master:
    image: pyspark-cluster:3.1.2
    ports:
      - "9090:8080"
      - "7077:7077"
    volumes:
      - ./input:/opt/spark-input
      - ./output:/opt/spark-output
      - ./app/:/opt/spark-app

    environment:
      - SPARK_LOCAL_IP=spark-master
      - SPARK_WORKLOAD=master

  spark-worker-a:
    image: pyspark-cluster:3.1.2
    ports:
      - "9091:8080"
      - "7000:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2G
      - SPARK_DRIVER_MEMORY=2G
      - SPARK_EXECUTOR_MEMORY=3G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-a
    volumes:
      - ./input:/opt/spark-input
      - ./output:/opt/spark-output
      - ./app/:/opt/spark-app

  spark-worker-b:
    image: pyspark-cluster:3.1.2
    ports:
      - "9092:8080"
      - "7001:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2G
      - SPARK_DRIVER_MEMORY=2G
      - SPARK_EXECUTOR_MEMORY=3G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-b
    volumes:
      - ./input:/opt/spark-input
      - ./output:/opt/spark-output
      - ./app/:/opt/spark-app